### ISSUE TITLE
First run of CubeDB

### ISSUE THREAD

**Issue by brtemik** [cubedb/cubedb#34]
Hello there! I am a newbie and got some problems dealing with CubeDB. I installed it according to the manual, but after I tryed to enter localhost:9998 and I've got an "HTTP 404 Not Found". It was unclear to me that everything is correct and I was supposed to go on localhost:9998/v1/stats to check if it is running. So it would be great if you notice this in the manual and make CubeDB a bit more user friendly :)
Also, after building a docker image and trying to run it I was reported such thing - "no main manifest attribute, in cubedb.jar". But I checked manifest.mf and it did have main-class link there.
My system: Ubuntu 16.04, Apache Maven 3.3.9, java-8-oracle.

**Comment by sztanko** [comment]
Good idea!

**Comment by sztanko** [comment]
Alternatively, I was thinking of redirecting '/' to '/stats'

**Comment by expobrain** [comment]
@sztanko I hate timed redirects :-)
